routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', function () {
    return redirect()->route('auth.login');
})->name('home');

Route::get('/dashboard', 'UserController@dashboard')->name('user.dashboard')->middleware('product-backlog');
Route::get('/profile/{username}', 'UserController@show')->name('user.profile');

Route::group(['prefix' => 'auth'], function () {
    Route::get('/register', 'Auth\AuthController@register')->name('auth.register');
    Route::get('/login', 'Auth\AuthController@login')->name('auth.login');
    Route::get('/dologin', 'Auth\AuthController@dologin')->name('auth.dologin');
    Route::get('/provider/{provider}', 'Auth\AuthController@redirectToProvider')->name('auth.provider');
    Route::get('/provider/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
    Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
});

Route::group(['prefix' => 'product-backlogs'], function () {
    Route::get('/list/{mode?}', 'ProductBacklogController@index')->name('product_backlogs.index');
    Route::get('/show/{slug}', 'ProductBacklogController@show')->name('product_backlogs.show');
    Route::get('/create', 'ProductBacklogController@create')->name('product_backlogs.create');
    Route::post('/store', 'ProductBacklogController@store')->name('product_backlogs.store');
    Route::get('/edit/{slug}', 'ProductBacklogController@edit')->name('product_backlogs.edit');
    Route::post('/update/{slug}', 'ProductBacklogController@update')->name('product_backlogs.update');
});

Route::group(['prefix' => 'sprints', 'middleware' => ['sprint.expired', 'global.activities']], function () {
    Route::get('/planning/{slug}/issues', 'IssueController@index')->name('issues.index');
    Route::get('/list/{mode?}/{slug_product_backlog?}', 'SprintController@index')->name('sprints.index');
    Route::get('/show/{slug}', 'SprintController@show')->name('sprints.show');
    Route::get('/create/{slug_product_backlog?}', 'SprintController@create')->name('sprints.create');
    Route::post('/store', 'SprintController@store')->name('sprints.store');
    Route::get('/edit/{slug}', 'SprintController@edit')->name('sprints.edit');
    Route::post('/update/{slug}', 'SprintController@update')->name('sprints.update');
    Route::delete('/destroy', 'SprintController@destroy')->name('sprints.destroy');
    Route::any('/status-update/{slug?}/{status?}', 'SprintController@statusUpdate')->name('sprints.status.update');
});

Route::group(['prefix' => 'user-stories'], function () {
    Route::get('/list/{mode?}/{slug_product_backlog?}', 'SprintController@index')->name('user_stories.index');
    Route::get('/show/{slug}', 'UserStoryController@show')->name('user_stories.show');
    Route::get('/create/{slug_product_backlog?}', 'UserStoryController@create')->name('user_stories.create');
    Route::post('/store', 'UserStoryController@store')->name('user_stories.store');
    Route::get('/edit/{slug}', 'UserStoryController@edit')->name('user_stories.edit');
    Route::delete('/destroy', 'UserStoryController@destroy')->name('user_stories.destroy');
    Route::post('/update/{slug}', 'UserStoryController@update')->name('user_stories.update');
});

Route::group(['prefix' => 'issues', 'middleware' => ['issue']], function () {
    Route::get('/show/{slug}', 'IssueController@show')->name('issues.show');
    Route::get('/create/{slug_sprint?}/{slug_user_story?}/{parent_id?}', 'IssueController@create')->name('issues.create');
    Route::post('/store', 'IssueController@store')->name('issues.store');
    Route::get('/edit/{slug}', 'IssueController@edit')->name('issues.edit');
    Route::post('/update/{slug}', 'IssueController@update')->name('issues.update');
    Route::delete('/destroy', 'IssueController@destroy')->name('issues.destroy');
    Route::any('/status-update/{slug?}/{status?}', 'IssueController@statusUpdate')->name('issues.status.update');
});

Route::group(['prefix' => 'user-issue'], function () {
    Route::get('/list/{username}/{slug_type?}/{mode?}', 'UserIssueController@index')->name('user_issue.index');
    Route::post('/update/{slug}', 'UserIssueController@update')->name('user_issue.update');
});

Route::group(['prefix' => 'issue-types'], function () {
    Route::get('/sprint/{slug_sprint}/{slug_type?}', 'IssueTypeController@index')->name('issue_types.index');
});

Route::group(['prefix' => 'commits'], function () {
    Route::get('/show/{sha}', 'CommitController@show')->name('commits.show');
});

Route::group(['prefix' => 'notes'], function () {
    Route::get('/--------', 'NoteController@store')->name('notes.show');
    Route::post('/store', 'NoteController@store')->name('notes.store');
    Route::get('/update/{slug}', 'NoteController@update')->name('notes.update');
    Route::get('/destroy/{id}', 'NoteController@destroy')->name('notes.destroy');
});

Route::group(['prefix' => 'comments'], function () {
    Route::get('/--------', 'CommentController@store')->name('comments.show');
    Route::get('/edit/{id}', 'CommentController@edit')->name('comments.edit');
    Route::post('/update/{id}', 'CommentController@update')->name('comments.update');
    Route::post('/store', 'CommentController@store')->name('comments.store');
    Route::get('/destroy/{id}', 'CommentController@destroy')->name('comments.destroy');
});

Route::group(['prefix' => 'labels'], function () {
    Route::get('/--------', 'LabelController@store')->name('labels.show');
    Route::get('/{model}/{slug_label?}', 'LabelController@index')->name('labels.index');
    Route::post('/store', 'LabelController@store')->name('labels.store');
});

Route::group(['prefix' => 'favorites'], function () {
    Route::get('/store/{type}/{id}', 'FavoriteController@store')->name('favorites.store');
    Route::get('/destroy/{type}/{id}', 'FavoriteController@destroy')->name('favorites.destroy');
});

Route::group(['prefix' => 'attachments'], function () {
    Route::get('/--------', 'AttachmentController@store')->name('attachments.show');
    Route::post('/store', 'AttachmentController@store')->name('attachments.store');
});

Route::group(['prefix' => 'teams'], function () {
    Route::get('/members', 'TeamController@index')->name('team.index');
});

Route::group(['prefix' => 'wizard'], function () {
    Route::get('/install', 'WizardController@install')->name('wizard.install');
    Route::get('/step1', 'WizardController@step1')->name('wizard.step1');
    Route::post('/step2', 'WizardController@step2')->name('wizard.step2');
    Route::get('/step3', 'WizardController@step3')->name('wizard.step3');
});

app/Models/Sprint.php
<?php
/**
 * GitScrum v0.1.
 *
 * @author  Renato Marinho <renato.marinho@s2move.com>
 * @license http://opensource.org/licenses/GPL-3.0 GPLv3
 */

namespace GitScrum\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use GitScrum\Scopes\GlobalScope;
use GitScrum\Scopes\SprintScope;

class Sprint extends Model
{
    use SoftDeletes;
    use SprintScope;
    use GlobalScope;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'sprints';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id', 'product_backlog_id', 'slug', 'title', 'description', 'version',
        'is_private', 'date_start', 'date_finish', 'state', 'color', 'position', 'closed_at', ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [];

    protected static function boot()
    {
        parent::boot();
    }

    public function productBacklog()
    {
        return $this->belongsTo(\GitScrum\Models\ProductBacklog::class, 'product_backlog_id', 'id');
    }

    public function branches()
    {
        return $this->hasMany(\GitScrum\Models\Branch::class, 'sprint_id', 'id');
    }

    public function issues()
    {
        return $this->hasMany(\GitScrum\Models\Issue::class, 'sprint_id', 'id')
            ->orderby('position', 'ASC');
    }

    public function issuesHasUsers()
    {
        $users = $this->issues->map(function ($issue) {
            return $issue->users;
        })->reject(function ($value) {
            return $value == null;
        })->flatten(1)->unique('id')->splice(0, 3);

        return $users->all();
    }

    public function comments()
    {
        return $this->morphMany(\GitScrum\Models\Comment::class, 'commentable')
            ->orderby('created_at', 'DESC');
    }

    public function attachments()
    {
        return $this->morphMany(\GitScrum\Models\Attachment::class, 'attachmentable');
    }

    public function notes()
    {
        return $this->morphMany(\GitScrum\Models\Note::class, 'noteable')
            ->orderby('position', 'ASC');
    }

    public function favorite()
    {
        return $this->morphOne(\GitScrum\Models\Favorite::class, 'favoriteable');
    }

    public function status()
    {
        return $this->hasOne(\GitScrum\Models\ConfigStatus::class, 'id', 'config_status_id');
    }

    public function pullrequests()
    {
        $prs = $this->branches->map(function ($branch) {
            if ($branch->pullrequests->count()) {
                return $branch->pullrequests;
            }
        })->reject(function ($value) {
            return $value == null;
        });

        return $prs->all();
    }

    public function totalAdditions()
    {
        $additions = $this->branches->map(function ($branch) {
            return $branch->commits;
        })->flatten(1)->map(function ($commit) {
            return $commit->files;
        })->flatten(1)->sum('additions');

        return $additions;
    }

    public function totalPullRequests()
    {
        $prs = $this->branches->map(function ($branch) {
            return $branch->pullrequests()->count();
        });

        return array_sum($prs->all());
    }

    public function workingDays($start = null)
    {
        $begin = strtotime(is_null($start) ? $this->attributes['date_start'] : $start);
        $end = strtotime($this->attributes['date_finish']);
        if ($begin > $end) {
            return 0;
        } else {
            $no_days = 0;
            $weekends = 0;
            while ($begin <= $end) {
                ++$no_days;
                $what_day = date('N', $begin);
                if ($what_day > 5) {
                    ++$weekends;
                }
                $begin += 86400;
            }
            $working_days = $no_days - $weekends;

            return $working_days;
        }
    }

    public function weeks($start = null)
    {
        $begin = Carbon::parse(is_null($start) ? $this->attributes['date_start'] : $start);
        $end = Carbon::parse($this->attributes['date_finish']);

        return round($begin->diffInDays($end) / 7);
    }

    public function getPSR2Errors()
    {
        $errors = 0;
        /*
        foreach ($this->branches as $branch) {
            foreach ($branch->commits as $commit) {
                foreach ($commit->files as $file) {
                    $errors += $file->filePhpcs->count();
                }
            }
        }
        */
        return $errors;
    }

    public function getEffort()
    {
        $effort = $this->issues->map(function ($issue) {
            return $issue->configEffort;
        })->sum('effort');

        return $effort;
    }

    public function getEffortAvg()
    {
        $effort = $this->issues->map(function ($issue) {
            return $issue->configEffort;
        })->avg('effort');

        return round($effort, 2);
    }

    public function activities()
    {
        $activities = $this->issues()
            ->with('statuses')->get()->map(function ($issue) {
                return $issue->statuses;
            })->flatten(1)->map(function ($statuses) {
                return $statuses;
            })->sortByDesc('created_at');

        $activities->splice(15);

        return $activities->all();
    }

    public function issueTypes()
    {
        $types = $this->issues->map(function ($issue) {
            return $issue->type;
        })->groupBy('slug')->map(function ($type) {
            return [
                'sprint' => $this->slug,
                'slug' => $type->first()->slug,
                'title' => $type->first()->title,
                'color' => $type->first()->color,
                'total' => $type->count(), ];
        })->sortByDesc('total')->all();

        return $types;
    }

    public function issueStatus()
    {
        $status = $this->issues->map(function ($issue) {
            return $issue->status;
        })->groupBy('slug')->all();

        return $status;
    }

    public function getVisibilityAttribute()
    {
        return $this->attributes['is_private'] ? trans('Private') : trans('Public');
    }

    public function getSlugAttribute()
    {
        return isset($this->attributes['slug']) ? $this->attributes['slug'] : '';
    }

    public function getTimeboxAttribute()
    {
        $date_start = isset($this->attributes['date_start']) ?
            Carbon::parse($this->attributes['date_start'])->toDateString() : '';
        $date_finish = isset($this->attributes['date_finish']) ?
            Carbon::parse($this->attributes['date_finish'])->toDateString() : '';

        return $date_start.' '.trans('to').' '.$date_finish;
    }
}

resources/views/sprints/create.blade.php
@section('title',  trans('Create Sprint'))

@extends('layouts.modal')

@section('content')

@include('partials.forms.sprint', ['route' => 'sprints.store'])

@endsection

resources/views/sprints/edit.blade.php
@section('title',  trans('Edit Sprint'))

@extends('layouts.modal')

@section('content')

    @include('partials.forms.sprint', ['route' => 'sprints.update', 'sprint' => $sprint ])

@endsection

resources/views/sprints/index-calendar.blade.php
@section('title',  trans('Sprints'))

@extends('layouts.master')

@section('breadcrumb')
<div class="col-lg-6">
    <h3>{{trans('Sprint Backlog - Calendar')}}</h3>
</div>
<div class="col-lg-6 text-right">
    <div class="btn-group">
        <a href="{{route('sprints.index', ['mode'=>'default'])}}"
            class="btn btn-sm btn-primary">
            {{trans('Mode List')}}</a>
        <a href="{{route('sprints.create')}}"
            class="btn btn-sm btn-primary"
            data-toggle="modal" data-target="#modalLarge">{{trans('Create Sprint Backlog')}}</a>
    </div>
</div>
@endsection

@section('content')

<div class="col-lg-12">

    <div class="ibox">
        <div class="ibox-content">
            <div id="calendar"></div>
        </div>
    </div>

</div>

<script>

$(function(){

    $('#calendar').fullCalendar({
        header: {
            right: 'prev,next',
            left: 'title'
        },
        editable: false,
        events: [
            @foreach ($sprints as $sprint)
            {
                title: '{{$sprint->title}}',
                start: new Date({{Carbon\Carbon::parse($sprint->date_start)->format('Y')}},
                                {{Carbon\Carbon::parse($sprint->date_start)->format('m')}},
                                {{Carbon\Carbon::parse($sprint->date_start)->format('d')}}),
                end: new Date(  {{Carbon\Carbon::parse($sprint->date_finish)->format('Y')}},
                                {{Carbon\Carbon::parse($sprint->date_finish)->format('m')}},
                                {{Carbon\Carbon::parse($sprint->date_finish)->format('d')}}),
                allDay: true,
                color: '#{{$sprint->color}}',
                url: '{{route('sprints.show',['slug'=>$sprint->slug])}}'
            },
            @endforeach
        ]
    });

});

</script>

@endsection

resources/views/sprints/index-default.blade.php
@section('title',  trans('Sprints'))

@extends('layouts.master')

@section('breadcrumb')
<div class="col-lg-6">
    <h3>{{trans('Sprint Backlog - List')}}</h3>
</div>
<div class="col-lg-6 text-right">
    <div class="btn-group">
        <a href="{{route('sprints.index', ['mode'=>'calendar'])}}" class="btn btn-sm btn-primary">
            {{trans('Mode Calendar')}}</a>
        <a href="{{route('sprints.create')}}"
            class="btn btn-sm btn-primary"
            data-toggle="modal" data-target="#modalLarge">{{trans('Create Sprint Backlog')}}</a>
    </div>
</div>
@endsection

@section('content')

<div class="col-lg-12">
    <div class="ibox">
        <div class="ibox-content">
            @include('partials.boxes.sprint', [ 'list' => $sprints ])
        </div>
    </div>
</div>

@endsection

resources/views/sprints/show.blade.php
@section('title',  trans('Sprint Backlog'))

@extends('layouts.master')

@section('breadcrumb')
<div class="col-lg-6">
    <h3>
        @if(isset($sprint->productBacklog->slug))
        <a href="{{route('product_backlogs.show', ['slug'=>$sprint->productBacklog->slug])}}">{{trans('Product Backlog')}}</a> &raquo;
        @endif
        <span>{{trans('Sprint Backlog')}}</span></h3>
</div>
<div class="col-lg-6 text-right">
    @include('partials.lnk-favorite', ['favorite' => $sprint->favorite, 'type' => 'sprint',
        'id' => $sprint->id, 'btnSize' => 'btn-sm font-bold', 'text' => trans('Favorite')])
    <a href="{{route('sprints.edit', ['slug'=>$sprint->slug])}}"
        class="btn btn-sm btn-primary"
        data-toggle="modal" data-target="#modalLarge">
        <i class="fa fa-pencil" aria-hidden="true"></i> {{trans('Edit Sprint Backlog')}}</a>
    <form action="{{route('sprints.destroy')}}" method="POST" class="form-delete pull-right">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE" />
        <input type="hidden" name="slug" value="{{$sprint->slug}}" />
        <button class="btn btn-sm btn-default" type="submit">
            <i class="fa fa-trash" aria-hidden="true"></i></a>
        </button>
    </form>
</div>
@endsection

@section('main-title')
<span class="label label-default">{{$sprint->visibility}}</span>
<span @if ( $sprint->closed_at ) style="text-decoration: line-through;" @endif>
    {{$sprint->title}}</span>

<div class="btn-group pull-right">
        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="background-color:#{{$sprint->status->color}}">
            <strong>{{$sprint->status->title}}</strong>
            &nbsp;
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @foreach ($configStatus as $value)
                @if($value->is_closed)
                    <li role="separator" class="divider"></li>
                @endif
            <li><a href="{{route('sprints.status.update', ['slug'=>$sprint->slug, 'status'=>$value->id])}}">
                {{$value->title}}</a></li>
            @endforeach
        </ul>
</div>
@endsection

@section('content')
<div class="col-lg-4">

    <a href="{{route('issues.index', ['slug'=>$sprint->slug])}}"
        class="btn btn-lg btn-block btn-warning"><strong>{{trans('Sprint Planning')}}</strong></a>

    <a href="{{route('issues.create', ['slug'=>$sprint->slug])}}"
        class="btn btn-block btn-primary"
        data-toggle="modal" data-target="#modalLarge"><strong>{{trans('Create Issue')}}</strong></a>

    @include('partials.boxes.chart-donut', ['list' => $sprint->issueStatus()])

    <div class="">
        @include('partials.boxes.progress-bar', [ 'percentage' => Helper::percentage($sprint, 'issues')])
    </div>

    <table class="table small m-b-xs">
        <tbody>
        <tr>
            <td width="50%">
                <h6>{{$sprint->getEffort()}} {{trans('effort')}}</h6>
            </td>
            <td width="50%">
                <h6>{{$sprint->getEffortAvg()}} {{trans('effort avg.')}}</h6>
            </td>
        </tr>
        <tr>
            <td width="50%">
                <h6>{{$sprint->issues->count()}} {{trans('issues')}}</h6>
            </td>
            <td width="50%"></td>
        </tr>
        </tbody>
    </table>

    <!--
    <div class="row m-t-sm">
        <div class="col-xs-4">
            <small class="stats-label">Additions</small>
            <h4>{{$sprint->totalAdditions()}}</h4>
        </div>
        <div class="col-xs-4">
            <small class="stats-label">PSR-2 Errors</small>
            <h4>{{$sprint->getPSR2Errors()}}</h4>
        </div>
        <div class="col-xs-4">
            <small class="stats-label">Bugs %</small>
            <h4>76.43%</h4>
        </div>
    </div>
    -->

    @include('partials.boxes.issue-type', ['list' => $sprint->issueTypes()])

    @include('partials.boxes.note', [ 'list' => $sprint,
        'type'=> 'sprint', 'title' => trans('Definition of Done Checklist for Sprint'),
        'percentage' => Helper::percentage($sprint, 'notes')])

    @include('partials.boxes.attachment', ['id' => $sprint->id, 'type' => 'sprint', 'list' => $sprint->attachments])

    @include('partials.boxes.team', ['title' => 'Team Members', 'list' => $sprint->issuesHasUsers()])

</div>

<div class="col-lg-8">

    <div class="well">

        <h4>{{trans('Date')}}: {{$sprint->date_start}} {{trans('to')}} {{$sprint->date_finish}}</h4>

        <p>{{$sprint->workingDays(date('Y-m-d'))}} {{str_plural('missing day', $sprint->workingDays(date('Y-m-d')))}} /
            {{$sprint->workingDays()}} {{str_plural('workdays', $sprint->workingDays())}}
            ( {{$sprint->weeks()}} {{str_plural('week', $sprint->weeks())}} )</p>

        <p class="">
            {{trans('Product Backlog')}}: <a href="{{route('product_backlogs.show', ['slug' => $sprint->productBacklog->slug])}}">
            <strong>{{$sprint->productBacklog->title}}</strong></a>
        </p>

    </div>

    @if(!empty($sprint->description))
    <p class="description">
        <small>{{trans('Description')}}</small>
        <span>{!! nl2br(e($sprint->description)) !!}<span>
    </p>
    @endif

    @include('partials.boxes.burndown', ['title' => ('Burndown Chart'), 'list' => Helper::burndown($sprint)])

    <div class="clearfix"></div>

        <div class="tabs-container mtl">

            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#tab-issues">
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    {{trans('Issues')}} ({{$sprint->issues->count()}})</a></li>
                <li class=""><a data-toggle="tab" href="#tab-comments">
                    <i class="fa fa-comments" aria-hidden="true"></i>
                    {{trans('Comments')}} ({{$sprint->comments->count()}})</a></li>
                <li><a data-toggle="tab" href="#tab-activities">
                    <i class="fa fa-rss" aria-hidden="true"></i>
                    {{trans('Activities')}}</a></li>
            </ul>

            <div class="tab-content">
                <div id="tab-issues" class="tab-pane active">
                    <div class="panel-body">
                        @include('partials.boxes.search-min')
                        @include('partials.boxes.issue', ['list' => $sprint->issues, 'messageEmpty' => trans('This does not have any issue yet')])
                    </div>
                </div>
                <div id="tab-comments" class="tab-pane">
                    <div class="panel-body">
                        @include('partials.forms.comment', ['id'=>$sprint->id, 'type'=>'sprint'])
                        @each('partials.lists.comments', $sprint->comments, 'comment', 'partials.lists.no-items')
                    </div>
                </div>
                <div id="tab-activities" class="tab-pane ">
                    <div class="panel-body">
                        <div class="feed-activity-list">
                            @each('partials.lists.activities-complete', $sprint->activities(), 'activity', 'partials.lists.no-items')
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

@endsection