routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', function () {
    return redirect()->route('auth.login');
})->name('home');

Route::get('/dashboard', 'UserController@dashboard')->name('user.dashboard')->middleware('product-backlog');
Route::get('/profile/{username}', 'UserController@show')->name('user.profile');

Route::group(['prefix' => 'auth'], function () {
    Route::get('/register', 'Auth\AuthController@register')->name('auth.register');
    Route::get('/login', 'Auth\AuthController@login')->name('auth.login');
    Route::get('/dologin', 'Auth\AuthController@dologin')->name('auth.dologin');
    Route::get('/provider/{provider}', 'Auth\AuthController@redirectToProvider')->name('auth.provider');
    Route::get('/provider/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
    Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
});

Route::group(['prefix' => 'product-backlogs'], function () {
    Route::get('/list/{mode?}', 'ProductBacklogController@index')->name('product_backlogs.index');
    Route::get('/show/{slug}', 'ProductBacklogController@show')->name('product_backlogs.show');
    Route::get('/create', 'ProductBacklogController@create')->name('product_backlogs.create');
    Route::post('/store', 'ProductBacklogController@store')->name('product_backlogs.store');
    Route::get('/edit/{slug}', 'ProductBacklogController@edit')->name('product_backlogs.edit');
    Route::post('/update/{slug}', 'ProductBacklogController@update')->name('product_backlogs.update');
});

Route::group(['prefix' => 'sprints', 'middleware' => ['sprint.expired', 'global.activities']], function () {
    Route::get('/planning/{slug}/issues', 'IssueController@index')->name('issues.index');
    Route::get('/list/{mode?}/{slug_product_backlog?}', 'SprintController@index')->name('sprints.index');
    Route::get('/show/{slug}', 'SprintController@show')->name('sprints.show');
    Route::get('/create/{slug_product_backlog?}', 'SprintController@create')->name('sprints.create');
    Route::post('/store', 'SprintController@store')->name('sprints.store');
    Route::get('/edit/{slug}', 'SprintController@edit')->name('sprints.edit');
    Route::post('/update/{slug}', 'SprintController@update')->name('sprints.update');
    Route::delete('/destroy', 'SprintController@destroy')->name('sprints.destroy');
    Route::any('/status-update/{slug?}/{status?}', 'SprintController@statusUpdate')->name('sprints.status.update');
});

Route::group(['prefix' => 'user-stories'], function () {
    Route::get('/list/{mode?}/{slug_product_backlog?}', 'SprintController@index')->name('user_stories.index');
    Route::get('/show/{slug}', 'UserStoryController@show')->name('user_stories.show');
    Route::get('/create/{slug_product_backlog?}', 'UserStoryController@create')->name('user_stories.create');
    Route::post('/store', 'UserStoryController@store')->name('user_stories.store');
    Route::get('/edit/{slug}', 'UserStoryController@edit')->name('user_stories.edit');
    Route::delete('/destroy', 'UserStoryController@destroy')->name('user_stories.destroy');
    Route::post('/update/{slug}', 'UserStoryController@update')->name('user_stories.update');
});

Route::group(['prefix' => 'issues', 'middleware' => ['issue']], function () {
    Route::get('/show/{slug}', 'IssueController@show')->name('issues.show');
    Route::get('/create/{slug_sprint?}/{slug_user_story?}/{parent_id?}', 'IssueController@create')->name('issues.create');
    Route::post('/store', 'IssueController@store')->name('issues.store');
    Route::get('/edit/{slug}', 'IssueController@edit')->name('issues.edit');
    Route::post('/update/{slug}', 'IssueController@update')->name('issues.update');
    Route::delete('/destroy', 'IssueController@destroy')->name('issues.destroy');
    Route::any('/status-update/{slug?}/{status?}', 'IssueController@statusUpdate')->name('issues.status.update');
});

Route::group(['prefix' => 'user-issue'], function () {
    Route::get('/list/{username}/{slug_type?}/{mode?}', 'UserIssueController@index')->name('user_issue.index');
    Route::post('/update/{slug}', 'UserIssueController@update')->name('user_issue.update');
});

Route::group(['prefix' => 'issue-types'], function () {
    Route::get('/sprint/{slug_sprint}/{slug_type?}', 'IssueTypeController@index')->name('issue_types.index');
});

Route::group(['prefix' => 'commits'], function () {
    Route::get('/show/{sha}', 'CommitController@show')->name('commits.show');
});

Route::group(['prefix' => 'notes'], function () {
    Route::get('/--------', 'NoteController@store')->name('notes.show');
    Route::post('/store', 'NoteController@store')->name('notes.store');
    Route::get('/update/{slug}', 'NoteController@update')->name('notes.update');
    Route::get('/destroy/{id}', 'NoteController@destroy')->name('notes.destroy');
});

Route::group(['prefix' => 'comments'], function () {
    Route::get('/--------', 'CommentController@store')->name('comments.show');
    Route::get('/edit/{id}', 'CommentController@edit')->name('comments.edit');
    Route::post('/update/{id}', 'CommentController@update')->name('comments.update');
    Route::post('/store', 'CommentController@store')->name('comments.store');
    Route::get('/destroy/{id}', 'CommentController@destroy')->name('comments.destroy');
});

Route::group(['prefix' => 'labels'], function () {
    Route::get('/--------', 'LabelController@store')->name('labels.show');
    Route::get('/{model}/{slug_label?}', 'LabelController@index')->name('labels.index');
    Route::post('/store', 'LabelController@store')->name('labels.store');
});

Route::group(['prefix' => 'favorites'], function () {
    Route::get('/store/{type}/{id}', 'FavoriteController@store')->name('favorites.store');
    Route::get('/destroy/{type}/{id}', 'FavoriteController@destroy')->name('favorites.destroy');
});

Route::group(['prefix' => 'attachments'], function () {
    Route::get('/--------', 'AttachmentController@store')->name('attachments.show');
    Route::post('/store', 'AttachmentController@store')->name('attachments.store');
});

Route::group(['prefix' => 'teams'], function () {
    Route::get('/members', 'TeamController@index')->name('team.index');
});

Route::group(['prefix' => 'wizard'], function () {
    Route::get('/install', 'WizardController@install')->name('wizard.install');
    Route::get('/step1', 'WizardController@step1')->name('wizard.step1');
    Route::post('/step2', 'WizardController@step2')->name('wizard.step2');
    Route::get('/step3', 'WizardController@step3')->name('wizard.step3');
});

app/Models/Commit.php
<?php
/**
 * GitScrum v0.1.
 *
 * @author  Renato Marinho <renato.marinho@s2move.com>
 * @license http://opensource.org/licenses/GPL-3.0 GPLv3
 */

namespace GitScrum\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Commit extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'commits';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['product_backlog_id', 'branch_id', 'user_id', 'issue_id', 'sha', 'url', 'message', 'html_url', 'date', 'tree_sha', 'tree_url', 'deleted_at'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [];

    protected $morphClass = 'commit';

    public function branch()
    {
        return $this->belongsTo(\GitScrum\Models\Branch::class, 'branch_id', 'id');
    }

    public function issue()
    {
        return $this->belongsTo(\GitScrum\Models\Issue::class, 'issue_id', 'id');
    }

    public function repository()
    {
        return $this->belongsTo(\GitScrum\Models\ProductBacklog::class, 'product_backlog_id', 'id');
    }

    public function user()
    {
        return $this->belongsTo(\GitScrum\Models\User::class, 'user_id', 'id');
    }

    public function pullRequestsHasCommits()
    {
        return $this->belongsToMany(\GitScrum\Models\PullRequestsHasCommit::class, 'pull_requests_has_commits', 'commit_id', 'pull_request_id');
    }

    public function files()
    {
        return $this->hasMany(\GitScrum\Models\CommitFile::class, 'commit_id', 'id');
    }

    public function totalLines()
    {
        $lines = $this->files->map(function ($file) {
            return count(preg_split('/\R/', $file->raw));
        });

        return array_sum($lines->all());
    }

    public function totalAdditions()
    {
        $additions = $this->files->map(function ($file) {
            return $file->additions;
        });

        return array_sum($additions->all());
    }

    public function totalChanges()
    {
        $changes = $this->files->map(function ($file) {
            return $file->changes;
        });

        return array_sum($changes->all());
    }

    public function totalDeletions()
    {
        $deletions = $this->files->map(function ($file) {
            return $file->deletions;
        });

        return array_sum($deletions->all());
    }

    public function totalPHPCS($type = 'ERROR')
    {
        $errors = $this->files->map(function ($file) use ($type) {
            return $file->filePhpcs()->where('type', '=', $type)->groupBy('type')->count();
        });

        return array_sum($errors->all());
    }

    public function getDateforhumansAttribute()
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $this->attributes['created_at'])->diffForHumans();
    }

    public function comments()
    {
        return $this->morphMany(\GitScrum\Models\Comment::class, 'commentable');
    }
}

resources/views/partials/boxes/attachment.blade.php
<div class="bx-attachment">
    <h4>{{trans('General Attachments')}}</h4>
    <ul class="list-group">
        @each('partials.lists.attachments-min', $list, 'attachment', 'partials.lists.no-items')
    </ul>

    @include('partials.forms.attachment', ['type' => $type, 'id' => $id])

</div>

resources/views/partials/boxes/bug-report.blade.php
<div class="feedback">
    <div class="tooltips">
        <div class="btn-group dropup">
            <button type="button" class="btn btn-success dropdown-toggle btn-circle btn-lg"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bug fa-2x" title="{{trans('Bug Report')}}"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-left dropdown-menu-form">
                <li>
                    <div class="report">
                        <h6 class="mbm">
                            <i class="fa fa-bug"></i>
                            {{trans('Report Bug')}}
                        </h6>
                        <form action="#" method="post">
                            {{ csrf_field() }}
                            <textarea required name="comment" class="form-control" placeholder="{{trans("Please tell us what bug or issue you've found, provide as much detail as possible")}}"></textarea>
                            <button class="btn btn-primary btn-block mtm">{{trans('Submit Report')}}</button>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/partials/boxes/burndown.blade.php
<div class="burndown">
    @if(isset($title))
    <h4>{{$title or trans('Burndown')}}</h4>
    @endif
    <div class="row">
        <canvas id="burndown" height="{{$height or '320'}}" class="col-md-12"></canvas>
    </div>
</div>


<script>
$(function() {

    var burndown = $("#burndown");

    var data = {
    labels: [ @foreach($list as $key=>$value) '{{$key}}', @endforeach ],
    datasets: [
        {
            label: "Issues",
            fill: true,
            lineTension: 0,
            backgroundColor: "rgba(219,68,83,0.4)",
            borderColor: "rgba(219,68,83,1)",
            pointBorderColor: "rgba(219,68,83,1)",
            pointBackgroundColor: "rgba(219,68,83,1)",
            pointBorderWidth: 1,
            pointHoverRadius: 6,
            pointRadius: 6,
            pointHitRadius: 2,
            data: [ @foreach($list as $key=>$value) '{{$value}}', @endforeach  ,0],
            spanGaps: false,
        }
    ]};

    var chartLine = new Chart(burndown, {
        type: 'line',
        data: data,
        options: {
            responsive: false,
            scales: {
                yAxes: [{
                    ticks: {
                        display: false
                    }
                }],
                xAxes: [{
                    ticks: {
                        display: false
                    }
                }]
            }
        }
    });

});

</script>

resources/views/partials/boxes/chart-donut.blade.php
@if( $list )
    @if( isset($title) )<h3>{{$title}}</h3>@endif

    <div class="mtm ptm">
        <canvas id="polarChart" height="380" class="col-md-12"></canvas>
    </div>

    <script>
    var data = {
        datasets: [{
            data: [ @foreach ($list as $key => $status) '{{$status->count()}}', @endforeach ],
            backgroundColor: [ @foreach ($list as $status) '#{{$status->first()->color}}', @endforeach ],
            label: 'Progress'
        }],
        labels: [ @foreach ($list as $key => $status) '{{$key}}', @endforeach ]
    };

    var polarChart = $("#polarChart");

    new Chart(polarChart, {
        data: data,
        type: 'polarArea',
    });
    </script>

@endif

resources/views/partials/boxes/issue-icons.blade.php
<span class="issue-icons">
@if($issue->commits->count())
<small title="{{trans('Commits')}}"><i class="fa fa-code" aria-hidden="true"></i> {{$issue->commits->count()}}</small>
&nbsp;&nbsp;
@endif

@if($issue->comments->count())
<small title="{{trans('Comments')}}"><i class="fa fa-comment-o" aria-hidden="true"></i> {{$issue->comments->count()}}</small>
&nbsp;&nbsp;
@endif

@if($issue->attachments->count())
<small title="{{trans('Attachments')}}"><i class="fa fa-file-o" aria-hidden="true"></i> {{$issue->attachments->count()}}</small>
&nbsp;&nbsp;
@endif

@if($issue->effort)
<small title="{{trans('Effort')}}"><i class="fa fa-tachometer" aria-hidden="true"></i> {{$issue->effort}}</small>
@endif

@if($issue->closed_at)
<small title="{{trans('Closed')}}" class="small-issue-closed">{{trans('closed')}} {{$issue->dateforhumans('closed_at')}}</small>
&nbsp;&nbsp;
@endif
</span>

resources/views/partials/boxes/issue-type.blade.php
<div class="mb20">
    <h4>{{trans('Issue Types')}}</h4>
    <ul class="tag-list list-inline">
        @each('partials.lists.issue-types', $list, 'list')
    </ul>
    <div class="clearfix"></div>
</div>

resources/views/partials/boxes/issue.blade.php
@if(!empty($list[0]))
<table class="table table-issue table-hover issue-tracker">
    <tbody>
    @each('partials.lists.issues', $list, 'list', 'partials.lists.no-items')
    </tbody>
</table>
@else
    @include('errors.notification-message', ['notification' => ['message' => $messageEmpty,
        'alert' => 'warning', 'class' => 'padding-none list-issue-empty']])
@endif

resources/views/partials/boxes/label.blade.php
<div class="">
    <h4>{{ $title or trans('Tags')}}</h4>
    @include('partials.forms.label', ['type' => $type, 'id' => $id])

    <ul class="tag-list list-inline" style="padding: 0">
        @each('partials.lists.labels', $list, 'list')
    </ul>

    <div class="clearfix"></div>
</div>

resources/views/partials/boxes/note.blade.php
<div class="notes">
    <h4>{{ $title or trans('Small Notes')}}</h4>

    @if(isset($percentage))
        @include('partials.boxes.progress-bar', [ 'percentage' => $percentage, 'title' => 'Completed'])
    @endif

    <div class="dd" id="nestable">
        <ul class="list-group">
            @each('partials.lists.notes-min', $list->notes, 'note')
        </ul>
    </div>

    @include('partials.forms.note', ['id'=> $list->id, 'type'=> $type])

</div>


<script>

var updateOutput = function (e) {

var list = e.length ? e : $(e.target),
     output = list.data('output');
if (window.JSON) {
 output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
} else {
 output.val('JSON browser support required for this demo.');
}
};

// activate Nestable for list 1
$('#nestable').nestable({
group: 1
}).on('change', updateOutput);

// activate Nestable for list 2
$('#nestable2').nestable({
group: 1
}).on('change', updateOutput);

// output initial serialised data
updateOutput($('#nestable').data('output', $('#nestable-output')));
updateOutput($('#nestable2').data('output', $('#nestable2-output')));

$('#nestable-menu').on('click', function (e) {
var target = $(e.target),
     action = target.data('action');
if (action === 'expand-all') {
 $('.dd').nestable('expandAll');
}
if (action === 'collapse-all') {
 $('.dd').nestable('collapseAll');
}
});
</script>

resources/views/partials/boxes/progress-bar.blade.php
<small class="progress-title">{{ $percentage }}% {{$title or trans('completed')}}</small>
<div class="progress progress-mini">
    <div style="width: {{ $percentage }}%;" class="progress-bar progress-success"></div>
</div>

resources/views/partials/boxes/search-min.blade.php
<div class="">

    <form method="get" action="" class="pull-right mail-search">
    <div class="form-group">
        <div class="input-group">
            <input class="form-control" type="text" name="{{@$query}}" value="{{@$search}}"
                autocomplete="off" placeholder="{{ $txtSearch or 'Search' }}">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">{{trans('Search')}}!</button>
            </span>
        </div>
    </div>
    </form>


    <a href="{{@$route}}" class="btn btn-default pull-left"><i class="fa fa-refresh"></i> {{trans('Refresh')}}</a>

    <div class="clearfix"></div>

</div>

@if ( @$search )
<p class="alert alert-success">{{trans('Search by')}} <strong>{{$search}}</strong></p>
@endif

resources/views/partials/boxes/sprint.blade.php
@if(!empty($list[0]))
    <table class="table-sprint-backlog table table-striped table-hover">
        <thead>
        <tr>
            @if(isset($column['thead_sprintFavorite']))
            <th width="10"></th>
            @endif

            @if(isset($column['thead_sprintLabels']))
            <th width="140"></th>
            @endif

            @if(isset($column['thead_sprintBacklog']))
            <th>{{trans('Sprint Backlog')}}</th>
            @endif

            @if(isset($column['thead_sprintProductBacklog']))
            <th class="text-right">{{trans('Product Backlog')}}</th>
            @endif
        </tr>
        </thead>
        <tbody>
            @each('partials.lists.sprints', $list, 'list', 'partials.lists.no-items')
        </tbody>
    </table>

    @if(!empty($list->links))
    {{ $list->links() }}
    @endif
@else
    @include('errors.notification-message', ['notification' => ['message' => trans('You are not a member of any sprint') .
        '. <a href="'.route('sprints.index').'" class="font-bold">'. trans('List Sprint Backlog') . '</a>',
        'alert' => 'warning', 'class' => 'padding-none list-sprint-empty']])
@endif

resources/views/partials/boxes/team.blade.php
<div class="team">
    <h4>{{ $title or trans('Members')}}</h4>
    <p class="small">{{ $subtitle or '' }}</p>
    <div class="users">
        @each('partials.lists.users-min', $list, 'user', 'partials.lists.no-items')
    </div>
</div>

resources/views/partials/boxes/user-story.blade.php
<div class="project-list">
    <table class="table table-hover">
        <tbody>
        @each('partials.lists.user-stories', $list, 'list', 'partials.lists.no-items')
        </tbody>
    </table>
    {{ $list->links() }}
</div>